experiment_name: "pcam_mlp_baseline"
seed: 42

data:
  dataset_type: "pcam"
  # TODO: download the dataset and set the relative path here
  data_path: "/home/scur2328/MLOps/assignment_1/data/surfdrive" 
  input_shape: [3, 96, 96]
  batch_size: 1
  num_workers: 2

model:
  hidden_units: [64, 32]
  dropout_rate: 0.2
  num_classes: 2

training:
  epochs: 5
  learning_rate: 0.001
  save_dir: "./experiments/results"
